if select(2, UnitClass("player")) ~= "ROGUE" then return end

local enable = false
local spn = select(1, GetSpellInfo(195627)) --可乘之机

--195627
local frame = CreateFrame("Frame") 
frame:RegisterEvent("UNIT_AURA")

frame:SetScript("OnEvent", function(self, event, arg1, arg2, arg3, arg4 ,arg5, ...)
	if not enable then return end

	if UnitBuff("player", spn) then
		SpellActivationOverlay_ShowOverlay(SpellActivationOverlayFrame,1,"TEXTURES\\SPELLACTIVATIONOVERLAYS\\SUDDEN_DEATH.BLP","LEFT",0.7,255,255,255,false,false) 
		--SpellActivationOverlay_ShowOverlay(SpellActivationOverlayFrame,2,"TEXTURES\\SPELLACTIVATIONOVERLAYS\\SUDDEN_DEATH.BLP","RIGHT",0.7,255,255,255,false,true) 
	else
		SpellActivationOverlay_HideOverlays(SpellActivationOverlayFrame,1)
		--SpellActivationOverlay_HideOverlays(SpellActivationOverlayFrame,2)
	end
end)

local SpecWatch = CreateFrame("Frame") 
SpecWatch:RegisterEvent("ACTIVE_TALENT_GROUP_CHANGED")
SpecWatch:RegisterEvent("PLAYER_ENTERING_WORLD")
SpecWatch:SetScript("OnEvent", function(self, event, arg1, arg2, arg3, arg4 ,arg5, ...)
	if GetSpecialization() == 2 then
		enable = true
	end
end)

--材质 
--"TEXTURES\\SPELLACTIVATIONOVERLAYS\\MASTER_MARKSMAN.BLP" 
--"TEXTURES\\SPELLACTIVATIONOVERLAYS\\FOCUS_FIRE.BLP" 
--"TEXTURES\\SPELLACTIVATIONOVERLAYS\\LOCK_AND_LOAD.BLP" 
--"TEXTURES\\SPELLACTIVATIONOVERLAYS\\BLOOD_SURGE.BLP" 
--"TEXTURES\\SPELLACTIVATIONOVERLAYS\\SWORD_AND_BOARD.BLP" 
--"TEXTURES\\SPELLACTIVATIONOVERLAYS\\SUDDEN_DEATH.BLP" 
--"TEXTURES\\SPELLACTIVATIONOVERLAYS\\MAELSTROM_WEAPON.BLP" 
--"TEXTURES\\SPELLACTIVATIONOVERLAYS\\FULMINATION.BLP" 
--"TEXTURES\\SPELLACTIVATIONOVERLAYS\\IMPACT.BLP" 
--"TEXTURES\\SPELLACTIVATIONOVERLAYS\\FROZEN_FINGERS.BLP" 
--"TEXTURES\\SPELLACTIVATIONOVERLAYS\\ARCANE_MISSILES.BLP" 
--"TEXTURES\\SPELLACTIVATIONOVERLAYS\\HOT_STREAK.BLP" 
--"TEXTURES\\SPELLACTIVATIONOVERLAYS\\BRAIN_FREEZE.BLP" 
--"TEXTURES\\SPELLACTIVATIONOVERLAYS\\SURGE_OF_LIGHT.BLP" 
--"TEXTURES\\SPELLACTIVATIONOVERLAYS\\MOLTEN_CORE.BLP" 
--"TEXTURES\\SPELLACTIVATIONOVERLAYS\\BACKLASH.BLP" 
--"TEXTURES\\SPELLACTIVATIONOVERLAYS\\IMP_EMPOWERMENT.BLP" 
--"TEXTURES\\SPELLACTIVATIONOVERLAYS\\NIGHTFALL.BLP" 
--"TEXTURES\\SPELLACTIVATIONOVERLAYS\\NATURES_GRACE.BLP" 
--"TEXTURES\\SPELLACTIVATIONOVERLAYS\\GENERICTOP_01.BLP" 
--"TEXTURES\\SPELLACTIVATIONOVERLAYS\\ECLIPSE_SUN.BLP" 
--"TEXTURES\\SPELLACTIVATIONOVERLAYS\\FURY_OF_STORMRAGE.BLP" 
--"TEXTURES\\SPELLACTIVATIONOVERLAYS\\ECLIPSE_MOON.BLP" 
--"TEXTURES\\SPELLACTIVATIONOVERLAYS\\SHOOTING_STARS.BLP" 
--"TEXTURES\\SPELLACTIVATIONOVERLAYS\\DARK_TRANSFORMATION.BLP" 
--"TEXTURES\\SPELLACTIVATIONOVERLAYS\\SUDDEN_DOOM.BLP" 
--"TEXTURES\\SPELLACTIVATIONOVERLAYS\\RIME.BLP" 
--"TEXTURES\\SPELLACTIVATIONOVERLAYS\\KILLING_MACHINE.BLP"{ 
--"TEXTURES\\SPELLACTIVATIONOVERLAYS\\GRAND_CRUSADER.BLP" 
--"TEXTURES\\SPELLACTIVATIONOVERLAYS\\ART_OF_WAR.BLP" 
--"TEXTURES\\SPELLACTIVATIONOVERLAYS\\DAYBREAK.BLP" 
--"TEXTURES\\SPELLACTIVATIONOVERLAYS\\HAND_OF_LIGHT.BLP"